ios: disable signing on some pods due to xcode upgrade
Fixes:
```
error: Signing for "RNImageCropPicker-QBImagePicker" requires a development team.
Select a development team in the Signing & Capabilities editor.
(in target 'RNImageCropPicker-QBImagePicker' from project 'Pods')
```

Signed-off-by: Jakub Sokołowski <jakub@status.im>